variable "region" {}
variable "vpc_cidr_block" {}
variable "environment_name" {}
variable "project_name" {}
variable "vpc_name" {}
variable "subnets_cidr" {}
variable "azs" {}
variable "igw_name" {}
variable "subnet_name" {}
variable "route_table_name" {}
variable "public_instance_name" {}
variable "s3_bucket_name" {}
variable "bucket_tag_name" {}
variable "role_name" {}
variable "policy_attached_role" {}
variable "policy_name" {}
variable "policy_description" {}
variable "instance_profile_name" {}
variable "key_name" {}
variable "public_key" {}
